[settings]
activate_aggressive = true
pin = true
idiomatic_version_file_enable_tools = ["python"]

[tools]
bat = "0.25.0"
carapace = "1.5.2"
jujutsu = "0.31.0"
lua = "5.1"
lua-language-server = "3.15.0"
ripgrep = "14.1.1"
sccache = "0.10.0"
usage = "latest"
